---
title: "Week4.042319"
author: "Rie"
date: "4/22/2019"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rethinking)
```

```{r Rcode4.1}
pos <- replicate(1000, sum(runif(16, -1,1)))
plot(density(pos))
```



```{r Rcode4.2}
prod(1 + runif(12, 0, 0.1))
```
```{r Rcode4.3}
growth <- replicate(10000, prod(1+runif(12, 0, 0.1)))
dens(growth, norm.comp = T)
```
```{r Rcode4.4}
big <- replicate(10000, prod(1+runif(12,0,0.5)))
small <- replicate(10000, prod(1+runif(12,0,0.01)))
dens(big, norm.comp = T)
dens(small, norm.comp = T)

```
```{r Rcode4.5}
log.big <- replicate(10000,log(prod(1+runif(12,0,0.5))))
dens(log.big, norm.comp = T)
```
```{r Rcode4 extra}
curve( exp(-x^2), from = -3, to = 3)
dnorm(0, 0, 0.1)
```

```{r Rcode4.6}
w <- 6 ; n <- 9;
p_grid <- seq(from=0, to=1, length.out = 100)
posterior <- dbinom(w, n, p_grid)*dunif(p_grid, 0, 1)
posterior <- posterior/sum(posterior)
dens(posterior)
```
```{r Rcode4.7}
data("Howell1")
d <- Howell1
head(d)
precis(d)
```
```{r Rcode4.11}
d2 <- d[d$age >= 18,]
dens(d2$height)
```
```{r Rcode4.12}
curve(dnorm(x, 178, 20), from = 100, to = 250)
```

```{r Rcode4.13}
curve(dunif(x, 0, 50), from = -10, to = 60)

```

```{r Rcode4.14}
sample_mu <- rnorm(1e4, 178, 20)
sample_sigma <- runif(1e4, 0, 50)
prior_h <- rnorm(1e4, sample_mu, sample_sigma)
dens(prior_h)

```

```{r Rcode4.15}
sample_mu <- rnorm(1e4, 178, 100)
prior_h <- rnorm(1e4, sample_mu, sample_sigma)
dens(prior_h)
```
```{r Rcode4.16}
mu.list <- seq(from=140, to=160, length.out=200)
sigma.list <- seq(from=4, to=9, length.out = 200)
post <- expand.grid(mu=mu.list, sigma=sigma.list)
post$LL <- sapply(1:nrow(post), function(i) sum( dnorm(
                  d2$height, 
                  mean = post$mu[i],
                  sd = post$sigma[i],
                  log = TRUE)))
post$prod <- post$LL + dnorm(post$mu, 178, 20, TRUE) +
  dunif(post$sigma, 0, 50, TRUE)
post$prob <- exp(post$prod - max(post$prod))
head(post)

```

```{r Rcode4.17&18}
contour_xyz(post$mu, post$sigma, post$prob)
image_xyz(post$mu, post$sigma, post$prob)
```

```{r Rcode4.19&20}
sample.rows <- sample(1:nrow(post), size = 1e4, replace = T ,
                      prob = post$prob)
sample.mu <- post$mu[sample.rows]
sample.sigma <- post$sigma[sample.rows]
plot(sample.mu, sample.sigma, cex=0.5, pch=16, col=col.alpha(rangi2,0.1))
```

```{r Rcode4.21}
dens(sample.mu)
dens(sample.sigma)
```
```{r Rcode4.22}
HPDI(sample.mu)
HPDI(sample.sigma)

```
```{r Rcode4.23}
d3 <- sample(d2$height, size=20)
d3
```
```{r Rcode4.24}
mu.list <- seq(from=150, to=170, length.out=200)
sigma.list <- seq(from=4, to=20, length.out = 200)
post2 <- expand.grid(mu=mu.list, sigma=sigma.list)
post2$LL <- sapply(1:nrow(post2), function(i) sum( dnorm(
                  d3, 
                  mean = post2$mu[i],
                  sd = post$sigma[i],
                  log = TRUE)))
post2$prod <- post2$LL + dnorm(post2$mu, 178, 20, TRUE) +
  dunif(post2$sigma, 0, 50, TRUE)
post2$prob <- exp(post2$prod - max(post2$prod))
sample2.rows <- sample(1:nrow(post2), size = 1e4, replace = T,
                       prob = post2$prob)
sample2.mu <- post2$mu[sample2.rows]
sample2.sigma <- post2$sigma[sample2.rows]
plot(sample2.mu, sample2.sigma, cex=0.5, pch=16, col=col.alpha(rangi2,0.1),
     xlab="mu", ylab="sigma")

```
```{r Rcode4.25}
dens(sample2.sigma, norm.comp = T)
```
```{r Rcode4.26}
d <- Howell1
d2 <- d[d$age>=18,]
head(d2)
```

```{r Rcode4.27}
flist <- alist(
  height ~dnorm(mu, sigma), 
  mu~ dnorm(178, 20),
  sigma ~ dunif(0,50)
)
```

```{r Rcode4.28}
m4.1 <- quap(flist , data=d2)
```

```{r Rcode4.29}
precis(m4.1)

```

```{r}
HPDI(sample.mu)
HPDI(sample.sigma)
```
```{r Rcode4.30}
start <- list(
  mu=mean(d2$height),
  sigma=sd(d2$height)
)
m4.1 <- quap(flist, data = d2, start = start)

```

