---
title: "Week8"
author: "Rie"
date: "5/21/2019"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rethinking)
```

```{r Rcode6.1}
N <- 200 # num grant proposals
p <- 0.1 #proportion to select

#uncorrelated newsworthiness and trustworthiness
nw <- rnorm(N)
tw <- rnorm(N)

#select top 10% of combined scores
s <- nw+tw #total score
q <- quantile(s, 1-p) #top 10% threshhold
selected <- ifelse(s >= q, T, F)
cor(tw[selected], nw[selected])

```
```{r Rcode6.2}
N <- 100  # number of indivisuals
set.seed(909)
height <- rnorm(N, 10, 2) #sim total height of each, #, mean, sd
leg_prop <- runif(N, 0.4, 0.5) #leg as propertion of height, uniform number, min and max
leg_left <- leg_prop*height+
  rnorm(N, 0, 0.02)  #sim left leg as proportion + error
leg_right <- leg_prop*height+
  rnorm(N, 0, 0.02) #sim right leg as proportion + error

d <- data.frame(height, leg_left, leg_right)

```




```{r Rcode6.3}

m6.1 <- quap(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- a + bl*leg_left+br*leg_right,
    a ~ dnorm(10, 100),
    bl ~ dnorm(2, 10),
    br ~ dnorm(2,10),
    sigma ~ dexp(1)
  ),
  data=d)
precis(m6.1)

```

```{r Rcode6.4}
plot(precis(m6.1))

```

```{r Rcode6.5}
post <- extract.samples(m6.1)
plot(bl ~ br, post, col=col.alpha(rangi2, 0.1), pch=16)

```

```{r Rcode6.6}
sum_blbr <- post$bl+post$br
dens(sum_blbr, col=rangi2, lwd=2, xlab="sum of bl and br")

```

```{r Rcode6.7}
m6.2 <- quap(
  alist(
    height ~ dnorm(mu, sigma), 
    mu <- a + bl*leg_left,
    a ~ dnorm(10, 100), 
    bl ~ dnorm(2, 10), 
    sigma ~ dexp(1)
  ), 
  data = d
)
precis(m6.2)

```

```{r Rcode6.8}
data(milk)
d <- milk
d$K <- scale(d$kcal.per.g)
d$F <- scale(d$perc.fat)
d$L <- scale(d$perc.lactose)

```

```{r Rcode6.9}
#kcal.per.g regressed on perc.fat
m6.3 <- quap(
   alist(
     K ~ dnorm(mu, sigma),
     mu <- a + bF*F, 
     a ~ dnorm(0, 0.2), 
     bF ~ dnorm(0, 0.5), 
     sigma ~ dexp(1)
      ),
   data = d
)

#kcal.per.g regressed on perc.lactose
m6.4 <- quap(
  alist(
    K ~ dnorm(mu, sigma), 
    mu <- a+bL*L,
    a ~ dnorm(0, 0.2),
    bL ~ dnorm(0, 0.5), 
    sigma ~ dexp(1)
  ), data = d
)

precis(m6.3)
precis(m6.4)
```

```{r Rcode6.10}
m6.5 <- quap(
  alist(
    K ~ dnorm(mu, sigma), 
    mu <- a + bF*F + bL*L, 
    a ~ dnorm(0, 0.2), 
    bF ~ dnorm(0, 0.5), 
    bL ~ dnorm(0, 0.5),
    sigma ~ dexp(1)
  ),
  data = d
)

precis(m6.5)
```

```{r Rcode6.11}
pairs( ~ kcal.per.g + perc.fat + perc.lactose, data = d, col=rangi2)

```

```{r Rcode6.12}
cor(d$perc.fat,d$perc.lactose)

```

```{r Rcode6.13}
data(milk)
d <- milk
sim.coll <- function(r=0.9){
  d$x <- rnorm(nrow(d), mean = r*d$perc.fat,
               sd = sqrt((1-r^2)*var(d$perc.fat)))
  m <- lm(kcal.per.g ~ perc.fat+x, data = d)
  sqrt(diag(vcov(m)))[2]
}
rep.sim.coll <- function(r=0.9, n=100){
  stddev <- replicate(n, sim.coll(r))
  mean(stddev)
}
r.seq <- seq(from=0, to=0.99, by=0.01)  
stddev <- sapply(r.seq, function(z) rep.sim.coll(r=z, n=100))
plot(stddev ~r.seq, type = "l", col=rangi2, lwd=2, xlab="correlation")

```

```{r Rcode6.14}
set.seed(71) 
#number of plants
N <- 100

#simulate initial heights
h0 <- rnorm(N, 10, 2)

#assign treatments and simulate fungus and growth
treatment <- rep(0:1, each=N/2)
fungus <- rbinom(N, size = 1, prob = 0.5 - treatment*0.4)
h1 <- h0 + rnorm(N, 5 - 3* fungus)

#compose a clean data fram
d <- data.frame(h0=h0, h1=h1, treatment=treatment, fungus=fungus)
precis(d)
```

```{r Rcode6.15}
sim_p <- rlnorm(1e04, 0, 0.25)
precis(data.frame(sim_p))

```

```{r Rcode6.16}
m6.6 <- quap(
  alist(
    h1 ~ dnorm(mu, sigma), 
    mu <- h0*p,
    p ~ dlnorm(0, 0.25), 
    sigma ~dexp(1)
  ), data = d
)
precis(m6.6)
```

```{r Rcode6.17}
m6.7 <- quap(
  alist(
    h1 ~ dnorm(mu, sigma), 
    mu <- h0*p, 
    p <- a + bt*treatment +bf*fungus,
    a~ dlnorm(0, 0.2),
    bt ~ dnorm(0, 0.5), 
    bf ~ dnorm(0, 0.5),
    sigma ~ dexp(1)
  ), data = d
)
precis(m6.7)
```

```{r Rcode6.18}
m6.8 <- quap(
  alist(
    h1 ~ dnorm(mu, sigma), 
    mu <- h0*p, 
    p <- a +bt*treatment, 
    a ~ dlnorm(0, 0.2), 
    bt ~ dnorm(0, 0.5), 
    sigma ~ dexp(1)
  ), data = d
)
precis(m6.8)
```

```{r Rcode6.19}
library(dagitty)
plant_dag <- dagitty("dag {
  H0 -> H1
  F -> H1
  T -> F
}")
coordinates(plant_dag) <- list(x=c(H0=0, T=2, F=1.5, H1=1),
                               y=c(H0=0, T=0, F=1, H1=2))
plot(plant_dag)
```

```{r Rcode6.20}
dseparated(plant_dag, "T", "H1")
dseparated(plant_dag, "T", "H1", "F")

```

```{r Rcode6.21}
impliedConditionalIndependencies(plant_dag)

```

```{r Rcode6.22}
d <- sim_happiness(seed = 1977, N_years = 1000)
precis(d)

```

```{r Rcode6.23}
d2 <- d[d$age>17, ]
d2$A <- (d2$age-18)/(65-18)

```

```{r Rcode6.24}
d2$mid <- d2$married +1 
m6.9 <- quap(
  alist(
    happiness ~dnorm(mu, sigma),
    mu <- a[mid] + bA*A,
    a[mid] ~ dnorm(0,1),
    bA ~ dnorm(0,2),
    sigma ~ dexp(1)
  ), data = d2
)
precis(m6.9, depth = 2)

```

```{r Rcode6.25}
m6.10 <- quap(
  alist(
    happiness ~ dnorm(mu, sigma), 
    mu <- a +bA*A, 
    a ~ dnorm(0, 1), 
    bA ~ dnorm(0, 2), 
    sigma ~ dexp(1)
  ), data = d2
)
precis(m6.10)
```

```{r Rcode6.26}
N <- 200  #number of grandparent-parent-child triads
b_GP <- 1 #direct effect of G on P
b_GC <- 0 #direct effect of G on C
b_PC <- 1 #direct effect of P on C
b_U <- 2 # direct effet of U on P and C

```


```{r Rcode6.27}
U <- 2*rbern(N, 0.5)-1
G <- rnorm(N)
P <- rnorm(N, b_GP*G+b_U*U)
C <- rnorm(N, b_PC*P+b_GC*G+b_U*U)
d <- data.frame(C=C, P=P, G=G, U=U)

```

```{r Rcode6.28}
m6.11 <- quap(
  alist(
    C~ dnorm(mu, sigma),
    mu <- a+b_PC*P + b_GC*G,
    a ~ dnorm(0,1), 
    c(b_PC, b_GC) ~ dnorm(0,1), 
    sigma ~ dexp(1)
  ), data = d
)

precis(m6.11)
```

```{r Rcode6.29}
m6.12 <- quap(
  alist(
    C ~dnorm(mu, sigma),
    mu <- a+b_PC*P + b_GC*G + b_U*U,
    a ~dnorm(0,1), 
    c(b_PC, b_GC, b_U) ~ dnorm(0,1), 
    sigma ~ dexp(1)
  ), data = d
)
precis(m6.12)
```

